# Generated by Django 4.0.4 on 2022-05-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('size', models.CharField(max_length=10, verbose_name='Размер')),
                ('sex', models.CharField(max_length=10, verbose_name='Пол')),
                ('category', models.CharField(max_length=20, verbose_name='Категория')),
                ('image', models.CharField(max_length=50, verbose_name='Картинка')),
                ('composition', models.CharField(max_length=50, verbose_name='Состав')),
                ('price', models.CharField(max_length=10, verbose_name='Стоимость')),
            ],
        ),
    ]
