# Generated by Django 4.0.4 on 2022-05-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Одежда', 'verbose_name_plural': 'Одежда'},
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.CharField(max_length=250, verbose_name='Картинка'),
        ),
    ]
